### ISSUE TITLE
Time Failed to Deserialize

### ISSUE THREAD

**Issue by cnsino** [secureCodeBox/defectdojo-client-java#29]
Cannot deserialize value of type `java.time.LocalDateTime` from String "2023-04-14T12:00:00.796635+08:00"
Text '2023-04-14T12:00:00.796635+08:00' could not be parsed, unparsed text found at index 26.

**Comment by J12934** [comment]
Hi @cnsino 
can you post some context on how you got to this exception?

**Comment by cnsino** [comment]
This error occurred when the nmap scan results were pushed to defectdojo, and the error was seen by looking at the job log. It may be that the tool cannot parse this parameter returned by dojo.

**Comment by Ilyesbdlala** [comment]
@cnsino Can you please more information on how to reproduce the error, because i am not able to do it.
 Are you using [secureCodeBox](https://github.com/secureCodeBox/secureCodeBox), our integrated scanner [nmap](https://www.securecodebox.io/docs/scanners/nmap) and our [defectdojo hook](https://www.securecodebox.io/docs/hooks/defectdojo) ? If that's the case, can you provide the relevant steps you took?
If not, please provide more information about your use case.

**Comment by cnsino** [comment]
When installing defectdojo, there is a parameter DD_TIME_ZONE, which defaults to UTC. If this is the case, no problem. But if you change this parameter to Asia/Shanghai or other values, this problem will appear.
